# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-21 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='change_stat',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='cmd_stat',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
