# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-23 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_hostcheck_smart'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='message_log',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
