# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexecmsg',
            name='addTime',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userexecmsg',
            name='msg',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userexecmsg',
            name='username',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
    ]
